config/routes.rb
Rails.application.routes.draw do
  resources :categories

  resources :tasks

  root 'tasks#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :tasks
  validates :name, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :category
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @categories_name = Category.all
    @categories = Category.pluck(:id)

    category_first = @categories.shift
    @tasks_first = Task.where(category_id: category_first).order(:priority)

    @tasks_tab = []
    @categories.each do |category_id|
      @tasks_tab << Task.where(category_id: category_id).order(:priority)
    end

    @task_count = Task.count    
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :start, :deadline, :description, :check, :priority, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :カテゴリ名 %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit('新規作成') %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>カテゴリ編集</h1>

<%= render 'form' %>

<%= link_to '確認', @category %> |
<%= link_to 'カテゴリ一覧に戻る', categories_path %>

app/views/categories/index.html.erb
<h1>カテゴリ一覧</h1>

<table>
  <thead>
    <tr>
      <th>カテゴリ名</th>
      <th colspan="3">コマンド</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td class="command"><%= link_to '確認', category %></td>
        <td class="command"><%= link_to '編集', edit_category_path(category) %></td>
        <td class="command"><%= link_to '削除', category, method: :delete, data: { confirm: 'このカテゴリを削除します。よろしいですか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'カテゴリの新規作成', new_category_path %>
<%= link_to 'タスク一覧に戻る', tasks_path %>

app/views/categories/new.html.erb
<h1>カテゴリの新規作成</h1>

<%= render 'form' %>

<%= link_to 'カテゴリ一覧に戻る', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>カテゴリ名:</strong>
  <%= @category.name %>
</p>

<%= link_to '編集する', edit_category_path(@category) %> |
<%= link_to 'カテゴリ一覧に戻る', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
  <script>
  $(function() {
  $("#tab .tabContents").hide();
  $("#tab .tabNav li:first a").addClass("active").show();
  $("#tab .tabContents:first").show();
  $("#tab .tabNav li").click(function() {
    $("#tab .tabNav li a").removeClass("active");
    $(this).find("a").addClass("active");
    $("#tab .tabContents").hide();
    var activeTab = $(this).find("a").attr("href");
    $(activeTab).fadeIn();
    return false;
  });
});
</script>

</head>
<body>
  <div id="layout">

    <%= yield %>

  </div>
</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :名前 %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :開始日時 %><br>
    <%= f.datetime_select :start %>
  </div>
  <div class="field">
    <%= f.label :締切日時 %><br>
    <%= f.datetime_select :deadline,:default => Time.now + 7.day %>
  </div>
  <div class="field">
    <%= f.label :詳細 %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :完了 %><br>
    <%= f.check_box :check %>
  </div>
  <div class="field">
    <%= f.label :優先度 %><br>
    <%= f.number_field :priority %>
  </div>
  <div class="field">
    <%= f.label :カテゴリ %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit('新規作成') %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>タスク編集</h1>

<%= render 'form' %>

<%= link_to '確認', @task %> |
<%= link_to 'タスク一覧に戻る', tasks_path %>

app/views/tasks/index.html.erb
<h1> 現在タスクは全部で<%= @task_count %>個です。</h1>

<br>
<div id="tab">
  <ul class="tabNav">
    <% @categories_name.each_with_index do |category,i| %>
      <li><a href="#contents0<%=i%>"><%= category.name %></a></li>
    <% end %>
  </ul>

    <div id="contents00" class="tabContents">
      <table>
        <thead>
          <tr>
            <th class="title">タスク名</th>
            <th>開始</th>
            <th>締切</th>
            <th class="description">詳細</th>
            <th class="check">完了</th>
            <th class="priority">優先度</th>
            <th class="categry">カテゴリ</th>
            <th colspan="3">コマンド</th>
          </tr>
        </thead>

        <tbody>
        <% @tasks_first.each do |task| %>
          <tr>
            <td class="title"><%= task.title %></td>
            <td><%= task.start %></td>
            <td><%= task.deadline %></td>
            <td><%= task.description %></td>
            <td><%= task.check %></td>
            <td><%= task.priority %></td>
            <td class="category"><%= Category.find(task.category_id).name %></td>
            <td class="command"><%= link_to '確認', task %></td>
            <td class="command"><%= link_to '編集', edit_task_path(task) %></td>
            <td class="command"><%= link_to '削除', task, method: :delete, data: { confirm: 'このタスクをなかったことにしますか？' } %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>



  <% @categories.each_with_index do |category,i| %>
    <div id="contents0<%=i+1%>" class="tabContents">

      <table>
        <thead>
          <tr>
            <th class="title">タスク名</th>
            <th>開始</th>
            <th>締切</th>
            <th class="description">詳細</th>
            <th class="check">完了</th>
            <th class="priority">優先度</th>
            <th class="categry">カテゴリ</th>
            <th colspan="3">コマンド</th>
          </tr>
        </thead>

        <tbody>
          <% @tasks_tab[i].each do |task| %>
            <tr>
              <td class="title"><%= task.title %></td>
              <td><%= task.start %></td>
              <td><%= task.deadline %></td>
              <td><%= task.description %></td>
              <td><%= task.check %></td>
              <td><%= task.priority %></td>
              <td class="category"><%= Category.find(task.category_id).name %></td>
              <td class="command"><%= link_to '確認', task %></td>
              <td class="command"><%= link_to '編集', edit_task_path(task) %></td>
              <td class="command"><%= link_to '削除', task, method: :delete, data: { confirm: 'このタスクをなかったことにしますか？' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>

<br>

<%= link_to 'タスクの新規作成', new_task_path %>
<%= link_to 'カテゴリの確認', categories_path %>

app/views/tasks/new.html.erb
<h1>タスクの新規作成</h1>

<%= render 'form' %>

<%= link_to 'タスク一覧に戻る', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>タスク名:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>開始:</strong>
  <%= @task.start %>
</p>

<p>
  <strong>締切:</strong>
  <%= @task.deadline %>
</p>

<p>
  <strong>詳細:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>完了:</strong>
  <%= @task.check %>
</p>

<p>
  <strong>優先度:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>カテゴリ:</strong>
  <%= Category.find(@task.category_id).name %>
</p>

<%= link_to '編集する', edit_task_path(@task) %> |
<%= link_to 'タスク一覧に戻る', tasks_path %>